---
title: "Real Data Study"
author: "Flora Le (flora.le@monash.edu)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(extraoperators)
library(compositions)
library(zCompositions)
library(multilevelcoda)
library(brms)
library(cmdstanr)
library(insight)
library(MASS)
library(bayestestR)

library(doFuture)
library(foreach)
library(parallel)
library(doRNG)
library(future)
library(multilevelTools)
library(JWileymisc)
library(bayesplot)

library(hrbrthemes)
library(wesanderson)
library(ggplot2)
library(ggsci)
library(ggpubr)
library(patchwork)
library(latex2exp)

options(digits = 2)

source("input.R")

col4 <- c("#A69188", "#C6BFB9", "#FAF7F3", "#A1B2C2", "#CFDAE2")
col <- c("#978787", "#C99696", "#C6BFB9", "#A1B2C2", "#647F9A") #lpa #mvpa #sb #wake #tst
# colf <- c("#BFBFBF", "#BFBFBF", "#BFBFBF", "#BFBFBF", "#BFBFBF")
colf <- c("#B2ABA6", "#B2ABA6", "#B2ABA6", "#B2ABA6", "#B2ABA6")
colf <- c("#978787", "#C99696", "#D1ACA5", "#A1B2C2", "#647F9A")

```

## Data scoring

```{r}
shs <- as.data.table(readRDS("/Volumes/shared/Behavioral-med-lab/StressHealthStudy/SHS Research Interns/Data/shs_daily_ggir.RDS"))
destress <- readRDS("/Volumes/shared/Behavioral-med-lab/DESTRESSStudy/Data/destress_daily_ggir.RDS")
aces <- readRDS("/Volumes/shared/Behavioral-med-lab/ACESStudy/Data/aces_daily_ggir.RDS")

d <- rbind(shs[, .(ID, UID = paste0("S", ID), SurveyDay, Survey, USURVEYID,
                   COPE_Appr, SLEEPY, SLEEPYNextDay, 
                   TIBg, Sleepg, WAKEg, MVPAg, LPAg, SBg)],
           destress[, .(ID, UID = paste0("D", ID), SurveyDay, Survey, USURVEYID,
                   COPE_Appr, SLEEPY, SLEEPYNextDay,
                   TIBg, Sleepg, WAKEg, MVPAg, LPAg, SBg)],
           aces[, .(ID, UID = paste0("A", ID), SurveyDay, Survey, USURVEYID,
                   COPE_Appr, SLEEPY, SLEEPYNextDay,
                   TIBg, Sleepg, WAKEg, MVPAg, LPAg, SBg)])

d <- d[complete.cases(d[, .(Sleepg, WAKEg, MVPAg, LPAg, SBg)])]
d <- d[WAKEg > 0] # make sure there is no 0s
d <- d[Survey == "Evening"] # select only when SLEEPYNextDay is avail

parts <- c("Sleepg", "WAKEg", "MVPAg", "LPAg", "SBg")

# remove NAs and 0s
any(apply(d[, parts, with = FALSE], 2, function(x) x == 0))
any(apply(d[, parts, with = FALSE], 2, function(x) is.na(x)))

# composition_imp <- lrEM(d[, parts5, with = FALSE], label = 0, dl = rep(1,5), ini.cov = "multRepl")
# d <- cbind(d[, -parts5, with = FALSE], composition_imp)
# check NA and 0
# d[which(is.na(d$Sleepg)), "ID"]
# d[which(is.na(d$WAKEg)), "ID"]
# d[which(is.na(d$SBg)), "ID"]
# d[which(is.na(d$LPAg)), "ID"]
# d[which(is.na(d$MVPAg)), "ID"]
# d[which(is.na(d$SLEEPY)), "ID"]

# mean(d$Sleepg)
# mean(d$WAKEg)
# mean(d$MVPAg)
# mean(d$LPAg)
# mean(d$SBg)
# 
# for (v in parts) {
#   plot(testDistribution(d[Survey == "Evening", get(v)]), varlab = v)
# }
# 
# d[Survey == "Evening", COPE_ApprNextDay := 
#     .SD[.(ID = ID, USURVEYID = USURVEYID + 1), .(COPE_Appr),
#         on = c("ID", "USURVEYID")]]
# 
# d[, c("COPE_Appr_NextDay") :=
#     .SD[.(UID = UID, Survey = Survey, SurveyDay = SurveyDay + 1),
#         .(COPE_Appr),
#         on = c("UID", "SurveyDay", "Survey")]]
```

## 5-part wake-wake composition model

```{r}
parts5 <- c("Sleepg", "WAKEg", "MVPAg", "LPAg", "SBg")
cilr5 <- compilr(d, sbp = sbp5,
                 parts = parts5, idvar = "UID")

m5 <- brmcoda(cilr5,
              SLEEPYNextDay ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + (1 | UID), 
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)
summary(m5)
# bayesplot::pp_check(m5$Model, ndraws = 5)
# launch_shinystan(m5mod)

submodel5 <- substitution(
  m5,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

thirty <- summary(submodel5, delta = 30)

realsumm <- summary(submodel5, delta = 30)
summary(submodel5, delta = 30)
# plotsub(submodel5$BetweenSub$Sleepg, "Between-person Sleep", "Sleepiness")
# plotsub(submodel5$BetweenSub$WAKEg, "Between-person WAKE", "Sleepiness")
# plotsub(submodel5$BetweenSub$MVPAg, "Between-person MVPA", "Sleepiness")
# plotsub(submodel5$BetweenSub$LPAg, "Between-person LPA", "Sleepiness")
# plotsub(submodel5$BetweenSub$SBg, "Between-person SB", "Sleepiness")
# 
# plotsub(submodel5$WithinSub$Sleepg, "Within-person Sleep", "Sleepiness")
# plotsub(submodel5$WithinSub$WAKEg, "Within-person WAKEg", "Sleepiness")
# plotsub(submodel5$WithinSub$MVPAg, "Within-person MVPA", "Sleepiness")
# plotsub(submodel5$WithinSub$LPAg, "Within-person LPA", "Sleepiness")
# plotsub(submodel5$WithinSub$SBg, "Within-person SB", "Sleepiness")

```

## Plots

```{r}

pb1 <- 
  plot(submodel5, ref = "grandmean", level = "between", to = "Sleepg") +
  scale_colour_manual(values = col[1:4], labels = c("LPA", "MVPA", "SB", "WAKE")) +
  scale_fill_manual(values = colf[1:4], labels = c("LPA", "MVPA", "SB", "WAKE")) +
  labs(x = "Minutes Reallocation to Total Sleep Time at Between level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
pb2 <- 
  plot(submodel5, ref = "grandmean", level = "between", to = "WAKEg") +
  scale_colour_manual(values = c(col[1:3], col[5]), labels = c("LPA", "MVPA", "SB", "TST")) +
  scale_fill_manual(values = c(colf[1:3], colf[5]), labels = c("LPA", "MVPA", "SB", "TST"))  +
  labs(x = "Minutes Reallocation to Awake in Bed at Between level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
pb3 <- 
  plot(submodel5, ref = "grandmean", level = "between", to = "MVPAg") +
  scale_colour_manual(values = c(col[1], col[3], col[5], col[4]), labels = c("LPA", "SB", "TST", "WAKE")) +
  scale_fill_manual(values = c(colf[1], colf[3], colf[5], colf[4]), labels = c("LPA", "SB", "TST", "WAKE")) +
  labs(x = "Minutes Reallocation to Moderate-to-Vigorous Physical Activity at Between level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
pb4 <- 
  plot(submodel5, ref = "grandmean", level = "between", to = "LPAg") +
  scale_colour_manual(values = c(col[2:3], col[5:4]), labels = c("MVPA", "SB", "TST", "WAKE")) +
  scale_fill_manual(values = c(colf[2:3], colf[5:4]), labels = c("MVPA", "SB", "TST", "WAKE"))  +
  labs(x = "Minutes Reallocation to Light Physical Activity at Between level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  )
pb5 <- 
  plot(submodel5, ref = "grandmean", level = "between", to = "SBg") +
  scale_colour_manual(values = c(col[1:2], col[5:4]), labels = c("LPA", "MVPA", "TST", "WAKE")) +
  scale_fill_manual(values = c(colf[1:2], colf[5:4]), labels = c("LPA", "MVPA", "TST", "WAKE")) +
  labs(x = "Minutes Reallocation to Sedentary Behaviour at Between level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
figureb <- ggarrange(pb1, pb2, pb3, pb4, pb5, nrow = 5, legend = "none")
# figureb <- annotate_figure(figureb,
#                            left = text_grob("Predicted change in sleepiness", size = 13, rot = 90, family = "Arial Narrow"))
pw1 <- 
  plot(submodel5, ref = "grandmean", level = "within", to = "Sleepg") +
  scale_colour_manual(values = col[1:4], labels = c("Light Physical Activity", "Moderate to Vigorous Physical Activity", "Sedentary Behaviour", "Awake in Bed")) +
  scale_fill_manual(values = colf[1:4], labels = c("Light Physical Activity", "Moderate to Vigorous Physical Activity", "Sedentary Behaviour", "Awake in Bed")) +
  labs(x = "Minutes Reallocation to Total Sleep Time at Within level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm"),
    legend.position = "bottom"
  ) 
pw2 <- 
  plot(submodel5, ref = "grandmean", level = "within", to = "WAKEg") +
  scale_colour_manual(values = c(col[1:3], col[5]), labels = c("LPA", "MVPA", "SB", "TST")) +
  scale_fill_manual(values = c(colf[1:3], colf[5]), labels = c("LPA", "MVPA", "SB", "TST"))  +
  labs(x = "Minutes Reallocation to Awake in Bed at Within level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
pw3 <- 
  plot(submodel5, ref = "grandmean", level = "within", to = "MVPAg") +
  scale_colour_manual(values = c(col[1], col[3], col[5], col[4]), labels = c("LPA", "SB", "TST", "WAKE")) +
  scale_fill_manual(values = c(colf[1], colf[3], colf[5], colf[4]), labels = c("LPA", "SB", "TST", "WAKE")) +
  labs(x = "Minutes Reallocation to Moderate-to-Vigorous Physical Activity at Within level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  ) 
pw4 <- 
  plot(submodel5, ref = "grandmean", level = "within", to = "LPAg") +
  scale_colour_manual(values = c(col[2:3], col[5:4]), labels = c("MVPA", "SB", "TST", "WAKE")) +
  scale_fill_manual(values = c(colf[2:3], colf[5:4]), labels = c("MVPA", "SB", "TST", "WAKE"))  +
  labs(x = "Minutes Reallocation to Light Physical Activity at Within level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm")
  )
pw5 <- 
  plot(submodel5, ref = "grandmean", level = "within", to = "SBg") +
  scale_colour_manual(values = c(col[1:2], col[5:4]), labels = c("Light Physical Activity", "Moderate to Vigorous Physical Activity", "Total Sleep Time", "Awake in Bed")) +
  scale_fill_manual(values = c(colf[1:2], colf[5:4]), labels = c("Light Physical Activity", "Moderate to Vigorous Physical Activity", "Total Sleep Time", "Awake in Bed")) +
  labs(x = "Minutes Reallocation to Sedentary Behaviour at Within level",
       y = " ") +
  scale_x_continuous(breaks = c(-30, 0, 30)) +
  scale_y_continuous(limits = c(-0.32, 0.32),
                     breaks = c(-0.25, 0, 0.25)) +
  hrbrthemes::theme_ipsum() +
  theme(
    axis.ticks        = element_blank(),
    panel.background  = element_blank(),
    panel.border      = element_blank(),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    plot.background   = element_rect(fill = "transparent", colour = NA),
    strip.text = element_blank(),
    axis.title.x      = element_text(size = 12),
    plot.margin = margin(.5, .5, .5, .5, "cm"),
    legend.position = "bottom"
  )
figurew <- ggarrange(pw1, pw2, pw3, pw4, pw5, nrow = 5, legend = "none")

figure <- ggarrange(figureb, figurew, ncol = 2, common.legend = TRUE, legend = "none")
#sae as 14:11
annotate_figure(figure, left = text_grob("Predicted change in Sleepiness", size = 13, rot = 90, family = "Arial Narrow", face = "bold"))
```




## 4-part wake-wake composition model

```{r}
parts4 <- c("TIBg", "MVPAg", "LPAg", "SBg")

cilr4 <- compilr(d, sbp = sbp4,
                 parts = parts4, idvar = "UID")

m4 <- brmcoda(cilr4,
              SLEEPYNextDay ~ bilr1 + bilr2 + bilr3 +
               wilr1 + wilr2 + wilr3  + (1 | UID),
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)
summary(m4$Model)
# bayesplot::pp_check(m5$Model, ndraws = 5)
# launch_shinystan(m5mod)

submodel4 <- substitution(
  m4,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

plotsub(submodel4$BetweenSub$TIBg, "Between-person TIB", "Sleepiness")
plotsub(submodel4$BetweenSub$MVPAg, "Between-person MVPA", "Sleepiness")
plotsub(submodel4$BetweenSub$LPAg, "Between-person LPA", "Sleepiness")
plotsub(submodel4$BetweenSub$SBg, "Between-person SB", "Sleepiness")

plotsub(submodel4$WithinSub$TIBg, "Within-person TIB", "Sleepiness")
plotsub(submodel4$WithinSub$MVPAg, "Within-person MVPA", "Sleepiness")
plotsub(submodel4$WithinSub$LPAg, "Within-person LPA", "Sleepiness")
plotsub(submodel4$WithinSub$SBg, "Within-person SB", "Sleepiness")

```

## 3-part wake-wake composition model

```{r}
d[, PAg := MVPAg + LPAg]
parts3 <- c("TIBg", "PAg", "SBg")

cilr3 <- compilr(d, sbp = sbp3,
                 parts = parts3, idvar = "UID")

m3 <- brmcoda(cilr3,
              SLEEPYNextDay ~ bilr1 + bilr2 +
               wilr1 + wilr2  + (1 | UID),
             cores = 4,
             chains = 4,
             iter = 3000,
             warmup = 500,
             seed = 123,
             backend = "cmdstanr"
)
summary(m3$Model)
# bayesplot::pp_check(m5$Model, ndraws = 5)
# launch_shinystan(m5mod)

submodel3 <- substitution(
  m3,
  delta = c(1:30),
  level = c("between", "within"),
  ref = "grandmean")

plotsub(submodel3$BetweenSub$TIBg, "Between-person TIB", "Sleepiness")
plotsub(submodel3$BetweenSub$PAg, "Between-person PA", "Sleepiness")
plotsub(submodel3$BetweenSub$SBg, "Between-person SB", "Sleepiness")

plotsub(submodel3$WithinSub$TIBg, "Within-person TIB", "Sleepiness")
plotsub(submodel3$WithinSub$PAg, "Within-person PA", "Sleepiness")
plotsub(submodel3$WithinSub$SBg, "Within-person SB", "Sleepiness")

```