---
title: "Simulation Study for multilevelcoda"
author: "Flora Le (flora.le@monash.edu)"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: sandstone
    highlight: zenburn
    toc: yes
    toc_float: yes
    collapsed: no
    smooth_scroll: no
    toc_depth: 4
    fig_width: 6
    fig_height: 4.5
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)

library(MASS)
library(data.table)
library(extraoperators)
library(compositions)
library(multilevelcoda)
library(brms)
library(cmdstanr)

library(doFuture)
library(foreach)
library(doRNG)
library(parallel)

library(ggplot2)
library(ggsci)
library(rsimsum) # https://cran.r-project.org/web/packages/rsimsum/vignettes/A-introduction.html
library(heatmaply)
library(ggthemes)
library(bayesplot)
# library(ggthemr)

# library(minted)
# opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
# options(formatR.arrow=TRUE,width=90, digits = 3)
data.table::setDTthreads(10)

input <- readRDS("input.RDS")
meanscovs <- input$meanscovs
prefit5 <- input$prefit5
prefit4 <- input$prefit4
prefit3 <- input$prefit3

source("input.R") # groundtruth, conditions and functions

### Heat plot
.heat_plot <- function(data, methodvar, by, stats) {
  ### Create a .dgm column
  if (!is.null(by)) {
    tmp <- lapply(by, function(x) data[[x]])
    data[[".dgm"]] <- do.call(paste, c(tmp, sep = ", "))
  } else {
    data[[".dgm"]] <- "Single DGM"
  }
  ### Build basic plot
  if (!is.null(methodvar)) {
    methodvar <- rlang::sym(methodvar)
    gg <- ggplot2::ggplot(data = data, ggplot2::aes(x = {{methodvar}}, y = .dgm, fill = est))
  } else {
    gg <- ggplot2::ggplot(data = data, ggplot2::aes(x = "Single Method", y = .dgm, fill = est)) +
      ggplot2::labs(x = "")
  }
  gg <- gg +
    ggplot2::geom_raster() +
    ggplot2::labs(y = "", fill = stats) +
    geom_text(data = data, aes(y = .dgm, label = round(est, digits = 2)), color = "black")

  ### Return plot
  return(gg)
}
```

# brmcoda Simulation Summary
## brmcodan() results data

```{r brmcoda-dat}

simsum_brmcoda_1 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_1.RDS")
simsum_brmcoda_2 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_2.RDS")
simsum_brmcoda_3 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_3.RDS")
simsum_brmcoda_4 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_4.RDS")
simsum_brmcoda_5 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_5.RDS")
simsum_brmcoda_6 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_6.RDS")
simsum_brmcoda_7 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_7.RDS")
simsum_brmcoda_8 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_brmcoda_8.RDS")

## separate by parts
simsum_brmcoda_d3 <- list()
simsum_brmcoda_d4 <- list()
simsum_brmcoda_d5 <- list()

for (j in 1:6) {
  simsum_brmcoda_d3[[j]] <- get(paste0("simsum_brmcoda_", j))[["out3"]]
  simsum_brmcoda_d4[[j]] <- get(paste0("simsum_brmcoda_", j))[["out4"]]
  simsum_brmcoda_d5[[j]] <- get(paste0("simsum_brmcoda_", j))[["out5"]]
}

simsum_brmcoda_d3 <- as.data.table(do.call(rbind, simsum_brmcoda_d3))
simsum_brmcoda_d4 <- as.data.table(do.call(rbind, simsum_brmcoda_d4))
simsum_brmcoda_d5 <- as.data.table(do.call(rbind, simsum_brmcoda_d5))
                                 
# add condition
simsum_brmcoda_d3[, condition := NA]
simsum_brmcoda_d3[, condition := ifelse(rint_sd == 1 & res_sd == 1, "base",  condition)]
simsum_brmcoda_d3[, condition := ifelse(rint_sd == sqrt(.5) & res_sd == sqrt(1.5), "REsmall_RESlarge",  condition)]
simsum_brmcoda_d3[, condition := ifelse(rint_sd == sqrt(1.5) & res_sd == sqrt(.5), "RElarge_RESsmall",  condition)]
simsum_brmcoda_d3[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(2), "REbase_RESlarge",  condition)]
simsum_brmcoda_d3[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(.5), "REbase_RESsmall",  condition)]

simsum_brmcoda_d4[, condition := NA]
simsum_brmcoda_d4[, condition := ifelse(rint_sd == 1 & res_sd == 1, "base",  condition)]
simsum_brmcoda_d4[, condition := ifelse(rint_sd == sqrt(.5) & res_sd == sqrt(1.5), "REsmall_RESlarge",  condition)]
simsum_brmcoda_d4[, condition := ifelse(rint_sd == sqrt(1.5) & res_sd == sqrt(.5), "RElarge_RESsmall",  condition)]
simsum_brmcoda_d4[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(2), "REbase_RESlarge",  condition)]
simsum_brmcoda_d4[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(.5), "REbase_RESsmall",  condition)]

simsum_brmcoda_d5[, condition := NA]
simsum_brmcoda_d5[, condition := ifelse(rint_sd == 1 & res_sd == 1, "base",  condition)]
simsum_brmcoda_d5[, condition := ifelse(rint_sd == sqrt(.5) & res_sd == sqrt(1.5), "REsmall_RESlarge",  condition)]
simsum_brmcoda_d5[, condition := ifelse(rint_sd == sqrt(1.5) & res_sd == sqrt(.5), "RElarge_RESsmall",  condition)]
simsum_brmcoda_d5[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(2), "REbase_RESlarge",  condition)]
simsum_brmcoda_d5[, condition := ifelse(rint_sd == 1 & res_sd == sqrt(.5), "REbase_RESsmall",  condition)]

```

## 3-part composition

```{r brmcoda-sum-b0-d3}
s_b0_d3 <- simsum(
  simsum_brmcoda_d3,
  estvarname = "b_Intercept",
  true = groundtruth3$b_Intercept,
  se = "se_Intercept",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_Intercept", "ul_Intercept")
)
summary(s_b0_d3)
# knitr::kable(tidy(summary(s_b0_d3)))

# plot
autoplot(summary(s_b0_d3), type = "lolly", stats = "bias")
autoplot(summary(s_b0_d3), type = "lolly", stats = "cover")

autoplot(summary(s_b0_d3), type = "forest", stats = "bias")
autoplot(summary(s_b0_d3), type = "forest", stats = "cover")

bias_b0_d3 <- tidy(s_b0_d3, stats = "bias")
bias_b0_d3$grp <- ifelse(bias_b0_d3$est < -0.5, "low",
                         ifelse(bias_b0_d3$est > 0.5, "high", "medium"))

.heat_plot(
  data = bias_b0_d3,
  methodvar = s_b0_d3$methodvar,
  by = s_b0_d3$by,
  stats = bias_b0_d3$stat[[1]]
) +
  scale_fill_gradient2(
    low = "#6D8B74",
    high = "#FAF7F3",
    na.value = NA
  ) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr1-d3}
s_bilr1_d3 <- simsum(
  simsum_brmcoda_d3,
  estvarname = "b_bilr1",
  true = groundtruth3$b_bilr1,
  se = "se_bilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr1", "ul_bilr1")
)
summary(s_bilr1_d3)

# plot
bias_bilr1_d3 <- tidy(s_bilr1_d3, stats = "bias")

.heat_plot(
  data = bias_bilr1_d3,
  methodvar = s_bilr1_d3$methodvar,
  by = s_bilr1_d3$by,
  stats = bias_bilr1_d3$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr2-d3}
s_bilr2_d3 <- simsum(
  simsum_brmcoda_d3,
  estvarname = "b_bilr2",
  true = groundtruth3$b_bilr2,
  se = "se_bilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr2", "ul_bilr2")
)
summary(s_bilr2_d3)

# plot
bias_bilr2_d3 <- tidy(s_bilr2_d3, stats = "bias")

.heat_plot(
  data = bias_bilr2_d3,
  methodvar = s_bilr2_d3$methodvar,
  by = s_bilr2_d3$by,
  stats = bias_bilr2_d3$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr1-d3}
s_wilr1_d3 <- simsum(
  simsum_brmcoda_d3,
  estvarname = "b_wilr1",
  true = groundtruth3$b_wilr1,
  se = "se_wilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr1", "ul_wilr1")
)
summary(s_wilr1_d3)

# plot
bias_wilr1_d3 <- tidy(s_wilr1_d3, stats = "bias")

.heat_plot(
  data = bias_wilr1_d3,
  methodvar = s_wilr1_d3$methodvar,
  by = s_wilr1_d3$by,
  stats = bias_wilr1_d3$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr2-d3}
s_wilr2_d3 <- simsum(
  simsum_brmcoda_d3,
  estvarname = "b_wilr2",
  true = groundtruth3$b_wilr2,
  se = "se_wilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr2", "ul_wilr2")
)
summary(s_wilr2_d3)

# plot
bias_wilr2_d3 <- tidy(s_wilr2_d3, stats = "bias")

.heat_plot(
  data = bias_wilr2_d3,
  methodvar = s_wilr2_d3$methodvar,
  by = s_wilr2_d3$by,
  stats = bias_wilr2_d3$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```

## 4-part composition

```{r brmcoda-sum-b0-d4}
s_b0_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_Intercept",
  true = groundtruth4$b_Intercept,
  se = "se_Intercept",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_Intercept", "ul_Intercept")
)
summary(s_b0_d4)

# plot
bias_b0_d4 <- tidy(s_b0_d4, stats = "bias")

.heat_plot(
  data = bias_b0_d4,
  methodvar = s_b0_d4$methodvar,
  by = s_b0_d4$by,
  stats = bias_b0_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr1-d4}
s_bilr1_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_bilr1",
  true = groundtruth4$b_bilr1,
  se = "se_bilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr1", "ul_bilr1")
)
summary(s_bilr1_d4)

# plot
bias_bilr1_d4 <- tidy(s_bilr1_d4, stats = "bias")

.heat_plot(
  data = bias_bilr1_d4,
  methodvar = s_bilr1_d4$methodvar,
  by = s_bilr1_d4$by,
  stats = bias_bilr1_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr2-d4}
s_bilr2_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_bilr2",
  true = groundtruth4$b_bilr2,
  se = "se_bilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr2", "ul_bilr2")
)
summary(s_bilr2_d4)

# plot
bias_bilr2_d4 <- tidy(s_bilr2_d4, stats = "bias")

.heat_plot(
  data = bias_bilr2_d4,
  methodvar = s_bilr2_d4$methodvar,
  by = s_bilr2_d4$by,
  stats = bias_bilr2_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr3-d4}
s_bilr3_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_bilr3",
  true = groundtruth4$b_bilr3,
  se = "se_bilr3",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr3", "ul_bilr3")
)
summary(s_bilr3_d4)

# plot
bias_bilr3_d4 <- tidy(s_bilr3_d4, stats = "bias")

.heat_plot(
  data = bias_bilr3_d4,
  methodvar = s_bilr3_d4$methodvar,
  by = s_bilr3_d4$by,
  stats = bias_bilr3_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr1-d4}
s_wilr1_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_wilr1",
  true = groundtruth4$b_wilr1,
  se = "se_wilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr1", "ul_wilr1")
)
summary(s_wilr1_d4)

# plot
bias_wilr1_d4 <- tidy(s_wilr1_d4, stats = "bias")

.heat_plot(
  data = bias_wilr1_d4,
  methodvar = s_wilr1_d4$methodvar,
  by = s_wilr1_d4$by,
  stats = bias_wilr1_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr2-d4}
s_wilr2_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_wilr2",
  true = groundtruth4$b_wilr2,
  se = "se_wilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr2", "ul_wilr2")
)
summary(s_wilr2_d4)

# plot
bias_wilr2_d4 <- tidy(s_wilr2_d4, stats = "bias")

.heat_plot(
  data = bias_wilr2_d4,
  methodvar = s_wilr2_d4$methodvar,
  by = s_wilr2_d4$by,
  stats = bias_wilr2_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr3-d4}
s_wilr3_d4 <- simsum(
  simsum_brmcoda_d4,
  estvarname = "b_wilr3",
  true = groundtruth4$b_wilr3,
  se = "se_wilr3",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr3", "ul_wilr3")
)
summary(s_wilr3_d4)

# plot
bias_wilr3_d4 <- tidy(s_wilr3_d4, stats = "bias")

.heat_plot(
  data = bias_wilr3_d4,
  methodvar = s_wilr3_d4$methodvar,
  by = s_wilr3_d4$by,
  stats = bias_wilr3_d4$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


## 5-part composition

```{r brmcoda-sum-b0-d5}
s_b0_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_Intercept",
  true = groundtruth5$b_Intercept,
  se = "se_Intercept",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_Intercept", "ul_Intercept")
)
summary(s_b0_d5)

# plot
bias_b0_d5 <- tidy(s_b0_d5, stats = "bias")

.heat_plot(
  data = bias_b0_d5,
  methodvar = s_b0_d5$methodvar,
  by = s_b0_d5$by,
  stats = bias_b0_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr1-d5}
s_bilr1_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_bilr1",
  true = groundtruth5$b_bilr1,
  se = "se_bilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr1", "ul_bilr1")
)
summary(s_bilr1_d5)

# plot
bias_bilr1_d5 <- tidy(s_bilr1_d5, stats = "bias")

.heat_plot(
  data = bias_bilr1_d5,
  methodvar = s_bilr1_d5$methodvar,
  by = s_bilr1_d5$by,
  stats = bias_bilr1_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr2-d5}
s_bilr2_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_bilr2",
  true = groundtruth5$b_bilr2,
  se = "se_bilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr2", "ul_bilr2")
)
summary(s_bilr2_d5)

# plot
bias_bilr2_d5 <- tidy(s_bilr2_d5, stats = "bias")

.heat_plot(
  data = bias_bilr2_d5,
  methodvar = s_bilr2_d5$methodvar,
  by = s_bilr2_d5$by,
  stats = bias_bilr2_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr3-d5}
s_bilr3_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_bilr3",
  true = groundtruth5$b_bilr3,
  se = "se_bilr3",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr3", "ul_bilr3")
)
summary(s_bilr3_d5)

# plot
bias_bilr3_d5 <- tidy(s_bilr3_d5, stats = "bias")

.heat_plot(
  data = bias_bilr3_d5,
  methodvar = s_bilr3_d5$methodvar,
  by = s_bilr3_d5$by,
  stats = bias_bilr3_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-bilr4-d5}
s_bilr4_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_bilr4",
  true = groundtruth5$b_bilr4,
  se = "se_bilr4",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_bilr4", "ul_bilr4")
)
summary(s_bilr4_d5)

# plot
bias_bilr4_d5 <- tidy(s_bilr4_d5, stats = "bias")

.heat_plot(
  data = bias_bilr4_d5,
  methodvar = s_bilr4_d5$methodvar,
  by = s_bilr4_d5$by,
  stats = bias_bilr4_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr1-d5}
s_wilr1_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_wilr1",
  true = groundtruth5$b_wilr1,
  se = "se_wilr1",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr1", "ul_wilr1")
)
summary(s_wilr1_d5)

# plot
bias_wilr1_d5 <- tidy(s_wilr1_d5, stats = "bias")

.heat_plot(
  data = bias_wilr1_d5,
  methodvar = s_wilr1_d5$methodvar,
  by = s_wilr1_d5$by,
  stats = bias_wilr1_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr2-d5}
s_wilr2_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_wilr2",
  true = groundtruth5$b_wilr2,
  se = "se_wilr2",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr2", "ul_wilr2")
)
summary(s_wilr2_d5)

# plot
bias_wilr2_d5 <- tidy(s_wilr2_d5, stats = "bias")

.heat_plot(
  data = bias_wilr2_d5,
  methodvar = s_wilr2_d5$methodvar,
  by = s_wilr2_d5$by,
  stats = bias_wilr2_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr3-d5}
s_wilr3_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_wilr3",
  true = groundtruth5$b_wilr3,
  se = "se_wilr3",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr3", "ul_wilr3")
)
summary(s_wilr3_d5)

# plot
bias_wilr3_d5 <- tidy(s_wilr3_d5, stats = "bias")

.heat_plot(
  data = bias_wilr3_d5,
  methodvar = s_wilr3_d5$methodvar,
  by = s_wilr3_d5$by,
  stats = bias_wilr3_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```


```{r brmcoda-sum-wilr4-d5}
s_wilr4_d5 <- simsum(
  simsum_brmcoda_d5,
  estvarname = "b_wilr4",
  true = groundtruth5$b_wilr4,
  se = "se_wilr4",
  methodvar = "condition",
  ref = "base",
  by = c("N", "K"),
  ci.limits = c("ll_wilr4", "ul_wilr4")
)
summary(s_wilr4_d5)

# plot
bias_wilr4_d5 <- tidy(s_wilr4_d5, stats = "bias")

.heat_plot(
  data = bias_wilr4_d5,
  methodvar = s_wilr4_d5$methodvar,
  by = s_wilr4_d5$by,
  stats = bias_wilr4_d5$stat[[1]]
) +
  scale_fill_gradient(low = "#6D8B74",
                      high = "#FAF7F3",
                      na.value = NA) +
  hrbrthemes::theme_ipsum()
```

## brmcoda sim plot

```{r}

# foreach (d = seq_along(3:5),
#          ) {
# .heat_plot(
#   data = df,
#   methodvar = s_bilr1$methodvar,
#   by = s_bilr1$by,
#   stats = df$stat[[1]]
# ) +
#   scale_fill_gradient(low = "#6D8B74",
#                       high = "#FAF7F3",
#                       na.value = NA) +
#   hrbrthemes::theme_ipsum()
# }
```

# substitution() Simulation Summary
## substitution() results data

```{r}

# simsum_sub_1 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_1.RDS")
# simsum_sub_2 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_2.RDS")
# simsum_sub_3 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_3.RDS")
# simsum_sub_4 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_4.RDS")
# simsum_sub_5 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_5.RDS")
# simsum_sub_6 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_6.RDS")
# simsum_sub_7 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_7.RDS")
# simsum_sub_8 <- readRDS("/Users/florale/Library/CloudStorage/OneDrive-MonashUniversity/PhD/Manuscripts/Project_multilevelcoda/multilevelcoda-sim-proj/Results/simsum_sub_8.RDS")
```




